# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h5Ugdv-GOSqqJ4bQDXb2mvDbibOFWrNI
"""

from vowpalwabbit import pyvw

import pandas as pd

def dict2str(dictionary,label):
  string = ''
  string += str(dictionary[label])
  string += '| '
  for i in dictionary:
    if i != label:
      string += str(i)+":"+str(dictionary[i])+' '
  return string

def convert(df,label):
  return [dict2str(dictionary,label) for dictionary in df.to_dict(orient='records')]
